### ISSUE TITLE
Error: Cannot start a runtime from within a runtime

### ISSUE THREAD

**Issue by AlexKnauth** [AlexKnauth/livesplit-one-druid#23]
```
[2024-11-13 02:42:41][PANIC][ERROR] panicked at C:\Users\Owner\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wasmtime-wasi-26.0.1\src\runtime.rs:108:15:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: livesplit_one::config::Config::setup_logging
   3: alloc::boxed::impl$50::call
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/alloc\src\boxed.rs:2245
      std::panicking::rust_panic_with_hook
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:805
   4: std::panicking::begin_panic_handler::closure$0
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:664
   5: std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\sys\backtrace.rs:170
   6: std::panicking::begin_panic_handler
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:662
   7: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:74
   8: tokio::runtime::context::runtime::enter_runtime
   9: wasmtime_wasi::runtime::in_tokio
  10: wasmtime::runtime::func::Caller<T>::with
  11: wasmtime::runtime::func::HostContext::array_call_trampoline
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: wasmtime_setjmp_26_0_1
  19: wasmtime::runtime::vm::traphandlers::catch_traps
  20: wasmtime::runtime::func::typed::TypedFunc<Params,Results>::call
  21: livesplit_auto_splitting::runtime::ExecutionGuard<T>::update
  22: livesplit_core::auto_splitting::run::{{closure}}
  23: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
  24: tokio::runtime::context::runtime::enter_runtime
  25: tokio::runtime::runtime::Runtime::block_on
  26: std::sys::backtrace::__rust_end_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: alloc::boxed::impl$48::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/alloc\src\boxed.rs:2231
      alloc::boxed::impl$48::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/alloc\src\boxed.rs:2231
      std::sys::pal::windows::thread::impl$0::new::thread_start
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\sys\pal\windows\thread.rs:55
  29: BaseThreadInitThunk
  30: RtlUserThreadStart
```

**Comment by AlexKnauth** [comment]
Fixed by https://github.com/AlexKnauth/livesplit-one-druid/commit/c165075241a7d3dc386b18da264abd1b3b64ea2c, released in 0.4.2
